Repository elastic-infra/go-remove-slowly, pull requests merged in 2024-02, with the labels that each got.

#11 Add an option to print simple output to STDOUT (instead of progress bar)
  Makefile
  cli/app.go
  cli/app_test.go
  filesystem/truncate.go
  filesystem/truncate_test.go
  output/output.go
Labels: size/M

#12 Fix CI
  .circleci/config.yml
  .go-version
  .goreleaser.yml
  Makefile
Labels: size/S

#13 Update modules
  filesystem/truncate.go
  go.mod
  go.sum
  tools.go
Labels: size/L
